### ISSUE TITLE
Error: This command needs 1 argument: chart name

### ISSUE THREAD

**Issue by maryxu** [komljen/helm-charts#1]
[root@xxx ~]# helm search efk
NAME                    CHART VERSION   APP VERSION     DESCRIPTION
akomljen-charts/efk     0.1.0           1.0             A Helm chart for EFK stack

[root@xxx efk]# helm install akomljen-charts/efk -name test --namespace=efk
Error: This command needs 1 argument: chart name

When I use helm to install efk, it prompts error of chart name. How should I install it correctly? Thanks for  your time and guide!

**Comment by komljen** [comment]
You are using the wrong command, try this:
```
helm install akomljen-charts/efk --name test --namespace=efk
```
