### ISSUE TITLE
[EFK] Erratic pod start

### ISSUE THREAD

**Issue by guilleironhack** [komljen/helm-charts#13]
I have installed and uninstalled the chart several times, but there is no way for the pods to start correctly. They seem to be crashing one after another mostly for not being able to resolve `elasticsearch-discovery-efk-cluster`. This happens even when the master node is apparently running correctly.

Any clues?

```
NAME                                                  READY     STATUS             RESTARTS   AGE
efk-kibana-76b967c8db-ll6jm                           0/1       CrashLoopBackOff   9          32m
es-client-efk-cluster-645d47fccc-wg4xp                1/1       Running            7          32m
es-data-efk-cluster-default-0                         1/1       Running            8          32m
es-master-efk-cluster-default-0                       0/1       CrashLoopBackOff   9          32m
es-operator-elasticsearch-operator-5977ff7c98-rwqng   1/1       Running            0          1d
fluent-bit-q4z5v                                      1/1       Running            0          32m
fluent-bit-qsql6                                      1/1       Running            0          32m
fluent-bit-vrqvx                                      1/1       Running            0          32m
```

Thanks!

**Comment by komljen** [comment]
You might have some DNS issues in your cluster. You could attach to data node `kubectl exec -it es-data-efk-cluster-default-0 -n <NAMESPACE> bash` and run `nslookup elasticsearch-discovery-efk-cluster`. It should resolve to cluster IP, the same address that you see here `kubectl get svc elasticsearch-discovery-efk-cluster -n <NAMESPACE>`.

**Comment by guilleironhack** [comment]
You're right. Something looks wrong with dns. Unfortunately I am just starting with kubernetes and couldn't be more lost. I'll keep investigating.

```
nslookup: can't resolve '(null)': Name does not resolve

nslookup: can't resolve 'elasticsearch-discovery-efk-cluster': Try again
```
