### ISSUE TITLE
Provide option to configure the node selector for elastic search

### ISSUE THREAD

**Issue by kanantha** [komljen/helm-charts#15]
Is there an option to mention the node selector in the efk stack helm chart for elasticsearch nodes?

**Comment by komljen** [comment]
Not possible AFAIK. cc @stevesloka

**Comment by stevesloka** [comment]
@komljen the operator lets you specify them now, probably need to push a release, but `master` has it now: https://github.com/upmc-enterprises/elasticsearch-operator/blob/master/pkg/apis/elasticsearchoperator/v1/cluster.go#L74

**Comment by komljen** [comment]
Aha, thank you! Yeah new release would be good. The last one was 6 month ago and there are some improvements in master.
