### ISSUE TITLE
Setting the 'master-volume-size' doesn't seem to have much effect

### ISSUE THREAD

**Issue by tonsV2** [komljen/helm-charts#25]
The following configuration of akomljen-charts/efk results in both master and data volume being 512Gi in size.

      elasticsearch:
        spec:
          master-volume-size: 10Gi
          data-volume-size: 512Gi

I tried to debug but my go skills are very limited. Any clue what I'm doing wrong?

**Comment by tonsV2** [comment]
To elaborate a bit more...

# Source: efk/charts/elasticsearch/templates/cluster.yaml
apiVersion: enterprises.upmc.com/v1
kind: ElasticsearchCluster
metadata:
  name: efk-cluster
  labels:
    app: elasticsearch
    chart: elasticsearch-0.1.6
    release: efk
    heritage: Tiller
spec:
  client-java-options: -Xms1024m -Xmx1024m
  client-node-replicas: 1
  data-java-options: -Xms2048m -Xmx2048m
  data-node-replicas: 1
  data-volume-size: 512Gi
  elastic-search-image: quay.io/pires/docker-elasticsearch-kubernetes:6.4.2
  master-java-options: -Xms2048m -Xmx2048m
  master-node-replicas: 1
  master-volume-size: 10Gi
  network-host: 0.0.0.0
  resources:
    limits:
      cpu: "1"
      memory: 3072Mi
    requests:
      cpu: 200m
      memory: 1024Mi
  snapshot:
    bucket-name: efk-snapshots
    bucketName: elasticsnapshots
    cron-schedule: 0 2 * * *
    enabled: false
    image: komljen/elasticsearch-cron:0.0.6
    repo-region: us-east-1
    repo-type: s3
    schedule: '@every 2m'
    scheduler-enabled: false
  storage:
    classProvisioner: volume.alpha.kubernetes.io/storage-class
    reclaimPolicy: Delete
    type: gp2
  use-ssl: false
  zones: []

**Comment by komljen** [comment]
The default ES operator version from this helm repo is `v0.3.0` https://github.com/komljen/helm-charts/blob/master/elasticsearch-operator/values.yaml#L6. Upgrade it to `v0.4.0` and it will work. Reference https://github.com/upmc-enterprises/elasticsearch-operator/releases.

**Comment by tonsV2** [comment]
Awesome!
