### ISSUE TITLE
Kibana is unable to connect to elasticsearch

### ISSUE THREAD

**Issue by ubongatluma** [komljen/helm-charts#5]
Error states
Unable to connect to Elasticsearch at http://elasticsearch-efk-cluster:9200.

I see that is defined in the yaml file. How do I get around this?
**hoping I get a quick response **

**Comment by komljen** [comment]
Are you pods running fine?

**Comment by marandalucas** [comment]
I had the same problem, i just needed to wait a little time because the pods have to start (it takes some seconds).
The helm chart run perfectly.
