### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by hitesh1907nayyar** [komljen/helm-charts#6]
Hi,

I have getting an error while installing efk stack 
D:\MACHINE LEARNING\Kubernates Microservices>helm --kubeconfig "D:\MACHINE LEARNING\Kubernates Microservices\hcl-kubeConfig" install --name efk --namespace logging akomljen-charts/efk
2018/11/24 20:43:20 warning: skipped value for env: Not a table.
2018/11/24 20:43:20 warning: skipped value for env: Not a table.
2018/11/24 20:43:20 warning: skipped value for env: Not a table.
2018/11/24 20:43:20 warning: skipped value for env: Not a table.
Error: validation failed: unable to recognize "": no matches for kind "ElasticsearchCluster" in version "enterprises.upmc.com/v1"

Will you able to please help ?

**Comment by komljen** [comment]
You skipped the step of installing ES operator in the blog post here https://akomljen.com/get-kubernetes-logs-with-efk-stack-in-5-minutes/. When you install it, `ElasticsearchCluster` will exist.

**Comment by hitesh1907nayyar** [comment]
Thanks. In addition I need to install Fluentd instead of Fluentbit. Will your chart support that ?

**Comment by komljen** [comment]
You would need to modify the chart to support it.
